"""Configuration module for Hologram."""

from hologram.config.constants import (
    CONVERGENCE_THRESHOLD,
    DEFAULT_DIMENSIONS,
    MAX_RESONATOR_ITERATIONS,
    REFUSAL_CONFIDENCE_THRESHOLD,
    RESPONSE_CONFIDENCE_THRESHOLD,
    SIMILARITY_THRESHOLD,
    VSA_MODEL,
)
from hologram.config.settings import Settings

__all__ = [
    "DEFAULT_DIMENSIONS",
    "VSA_MODEL",
    "RESPONSE_CONFIDENCE_THRESHOLD",
    "REFUSAL_CONFIDENCE_THRESHOLD",
    "SIMILARITY_THRESHOLD",
    "MAX_RESONATOR_ITERATIONS",
    "CONVERGENCE_THRESHOLD",
    "Settings",
]
